name: responsive_scaffold_card
description: Scaffold responsivo para mobile, tablet e web
version: 0.0.1
author:
homepage: github.com/gustavofagundespaixao

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: